### ISSUE TITLE
Issue, Getting Error

### ISSUE THREAD

**Issue by SaiRev0** [nkeil/prisma-extension-random#16]
```
import { PrismaClient } from '@prisma/client'
import 'server-only'
import prismaRandom from 'prisma-extension-random'

declare global {
  // eslint-disable-next-line no-var, no-unused-vars
  var cachedPrisma: PrismaClient
}

let prisma: PrismaClient
if (process.env.NODE_ENV === 'production') {
  prisma = new PrismaClient().$extends(prismaRandom())
} else {
  if (!global.cachedPrisma) {
    global.cachedPrisma = new PrismaClient().$extends(prismaRandom())
  }
  prisma = global.cachedPrisma
}

export const db = prisma

```

This is the code I have and I m getting this error 

```
Type 'DynamicClientExtensionThis<TypeMap<InternalArgs & { result: {}; model: { $allModels: { findRandom: () => <T, A>(this: T, args?: (Exact<A, Args<T, "findFirst">> & object) | undefined) => Promise<...>; findManyRandom: () => <T_1, TWhere, TSelect, TUnique extends string>(this: T_1, num: number, args?: { ...; } | undefi...' is missing the following properties from type 'PrismaClient<PrismaClientOptions, never, DefaultArgs>': $on, $usets(2739)
```

So How I can I extend the PrismaClient type ??

**Comment by nkeil** [comment]
The issue here is that the extended prisma client isn't the same type as the standard `PrismaClient` type, so you can't type `cachedPrisma` or `prisma` as `PrismaClient`. I'd recommend getting the extended prisma client type like this:
```js
const getPrismaClient = () => {
  return new PrismaClient().$extends(prismaRandom());
};
export type ExtendedPrismaClient = ReturnType<typeof getPrismaClient>;

declare global {
  // eslint-disable-next-line no-var, no-unused-vars
  var cachedPrisma: ExtendedPrismaClient;
}

let prisma: ExtendedPrismaClient;
if (process.env.NODE_ENV === "production") {
  prisma = getPrismaClient();
} else {
  if (!global.cachedPrisma) {
    global.cachedPrisma = getPrismaClient();
  }
  prisma = global.cachedPrisma;
}

export const db = prisma;
```

**Comment by SaiRev0** [comment]
@nkeil Thanks for this. It worked for me, but since I'm using PrismaAdapter, I'm getting the same error In that 

My code:-

```
export const authOptions: NextAuthOptions = {
  adapter: PrismaAdapter(db),
}
```
`db` is what I'm getting from the code you wrote above

Error:

```
Argument of type 'DynamicClientExtensionThis<TypeMap<InternalArgs & { result: {}; model: { $allModels: { findRandom: () => <T, A>(this: T, args?: (Exact<A, Args<T, "findFirst">> & object) | undefined) => Promise<...>; findManyRandom: () => <T_1, TWhere, TSelect, TUnique extends string>(this: T_1, num: number, args?: { ...; } | undefi...' is not assignable to parameter of type 'PrismaClient<PrismaClientOptions, never, DefaultArgs>'.
  Type 'DynamicClientExtensionThis<TypeMap<InternalArgs & { result: {}; model: { $allModels: { findRandom: () => <T, A>(this: T, args?: (Exact<A, Args<T, "findFirst">> & object) | undefined) => Promise<...>; findManyRandom: () => <T_1, TWhere, TSelect, TUnique extends string>(this: T_1, num: number, args?: { ...; } | undefi...' is missing the following properties from type 'PrismaClient<PrismaClientOptions, never, DefaultArgs>': $on, $usets(2345)
```

**Comment by SaiRev0** [comment]
> The issue here is that the extended prisma client isn't the same type as the standard `PrismaClient` type, so you can't type `cachedPrisma` or `prisma` as `PrismaClient`. I'd recommend getting the extended prisma client type like this:
> 
> ```js
> const getPrismaClient = () => {
>   return new PrismaClient().$extends(prismaRandom());
> };
> export type ExtendedPrismaClient = ReturnType<typeof getPrismaClient>;
> 
> declare global {
>   // eslint-disable-next-line no-var, no-unused-vars
>   var cachedPrisma: ExtendedPrismaClient;
> }
> 
> let prisma: ExtendedPrismaClient;
> if (process.env.NODE_ENV === "production") {
>   prisma = getPrismaClient();
> } else {
>   if (!global.cachedPrisma) {
>     global.cachedPrisma = getPrismaClient();
>   }
>   prisma = global.cachedPrisma;
> }
> 
> export const db = prisma;
> ```

Also I think you should mention this in the documentation as well for people using typescript.

**Comment by nkeil** [comment]
@SaiRev0 Does the `NextAuthOptions` code work if you ignore the type error? If it's just expecting the non-extended prisma client then it should work with the extended one.

You could do: `PrismaAdapter(db as unknown as PrismaClient)` anywhere where the type isn't matching.

On your second point, I think it belongs more on prisma docs than mine, since it would likely apply to any prisma extension.
