### ISSUE TITLE
findManyRandom lose the type

### ISSUE THREAD

**Issue by voignar** [nkeil/prisma-extension-random#17]
If use findManyRandom lose the type

![image](https://github.com/nkeil/prisma-extension-random/assets/2969205/1bd6cc78-ee82-4374-b613-113e6541c29c)
![image](https://github.com/nkeil/prisma-extension-random/assets/2969205/0cb4909f-1168-4a8b-b000-eb8ddb07fda2)

**Comment by nkeil** [comment]
@voignar Thanks for filing an issue! This should be fixed after the latest v0.2.2 release. Feel free to reopen if there's any other problems.
